### ISSUE TITLE
I never win!

### ISSUE THREAD

**Issue by simiaosimis** [erikathea/grails-connect-four-sample#1]
Even when making four in a row or any direction I don't get the alert with the win message.

**Comment by erikathea** [comment]
Sorry for that. I left the code in the middle of refactoring. Anyway, I updated the js file. 
Thanks for commenting. I totally forgot about this project.

**Comment by simiaosimis** [comment]
I had already fixed it, I would pull request but it was just a couple lines. Thank you for the answer.
